apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- https://github.com/ionos-cloud/cluster-api-provider-proxmox//templates/clusterclass-cilium-with-shared-ippool/base/?ref=main